name: todo
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^7.3.0
  equatable: ^2.0.3
  sqflite: ^2.0.0+4
  flutter_slidable: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: IRANSansMobile
      fonts:
        - asset: assets/fonts/IRANSansMobile.ttf
        - asset: assets/fonts/IRANSansMobileBold.ttf
        - asset: assets/fonts/IRANSansMobileLight.ttf
        - asset: assets/fonts/IRANSansMobileMedium.ttf
        - asset: assets/fonts/IRANSansMobileUltraLight.ttf
